postgres:
  image: mdillon/postgis:9.4-2.1
  ports:
    - "5432:5432"
  volumes:
    - cornerwise_db:/var/lib/postgresql/9.4/main

redis:
  image: redis:latest

cornerwise:
  build: .
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
  environment:
    - PYTHONUNBUFFERED=1
    - REDIS_HOST=redis
    - POSTGRES_HOST=postgres
