version: '2'

services:
  cornerwise:
    build: .
    image: cornerwise
    depends_on:
      - postgres
      - redis
    environment:
      PYTHONUNBUFFERED: "1"
      REDIS_HOST: "redis"
      POSTGRES_HOST: "postgres"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/cornerwise/google_credentials.json"
    links:
      - postgres
      - redis
    command: bash /app/start.sh
    volumes:
      - runinfo:/runinfo
  celery:
    image: cornerwise
    depends_on:
      - cornerwise
      - postgres
      - redis
    command: bash /app/celery_start.sh
  postgres:
    image: mdillon/postgis:9.4
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
  data:
    driver: local
  runinfo:
    driver: local
